# Generated by Django 4.1.2 on 2023-02-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_finalprice_alter_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic4',
            new_name='pic',
        ),
    ]
